import localFont from 'next/font/local'
import './globals.css'

const cabinet = localFont({
  src: [
    {
      path: './fonts/CabinetGrotesk-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/CabinetGrotesk-Light.otf',
      weight: '400',
      style: 'italic',
    },
    {
      path: './fonts/CabinetGrotesk-Medium.otf',
      weight: '400',
      style: 'italic',
    },
    {
      path: './fonts/CabinetGrotesk-Bold.otf',
      weight: '700',
      style: 'bold',
    },
    {
      path: './fonts/CabinetGrotesk-Extrabold.otf',
      weight: '800',
      style: 'italic',
    },
  ],
})

export const metadata = {
  title: 'Farmiz',
  description: 'Generated by create next app',
  content: 'width=device-width, initial-scale=1',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cabinet.className} suppressHydrationWarning={true}>{children}</body>
    </html>
  )
}
